import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import { JsonController, Post, Get, Body, Res } from 'routing-controllers';
import { Service } from 'typedi';

import { config } from '../../config/config.js';
import { ErrorCode } from '../../constants/error-codes.js';
import { UserService } from '../../services/user.service.js';
import { StorageService } from '../../services/storage.service.js';
import { logger } from '../../utils/logger.js';
import { ResponseUtil as ResponseUtility } from '../../utils/response.js';

import type { RegisterDto, LoginDto, LoginResponseDto } from '@x-console/dto';
import type { Response } from 'express';

@Service()
@JsonController('/api/v1/auth')
export class AuthV1Controller {
  constructor(
    private userService: UserService,
    private storageService: StorageService
  ) {}

  @Get('/config')
  getConfig() {
    return ResponseUtility.success({ allowRegistration: config.allowRegistration });
  }

  @Post('/register')
  async register(@Body() userData: RegisterDto, @Res() response: Response) {
    try {
      // Check if registration is allowed
      if (!config.allowRegistration) {
        return ResponseUtility.error(ErrorCode.FORBIDDEN, 'Registration is not allowed');
      }
      // Validate required fields
      if (!userData.email || !userData.password || !userData.username) {
        return ResponseUtility.error(
          ErrorCode.PARAMS_ERROR,
          'Email, password, and username are required'
        );
      }

      // Validate email format
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(userData.email)) {
        return ResponseUtility.error(ErrorCode.PARAMS_ERROR, 'Invalid email format');
      }

      // Hash password with bcrypt
      const hashedPassword = await bcrypt.hash(userData.password, 10);

      // Create new user
      const user = await this.userService.createUser({
        id: '', // Will be generated by service
        email: userData.email,
        password: hashedPassword,
        username: userData.username.trim(),
      });

      // Generate JWT token
      const token = jwt.sign(
        {
          id: user.id,
        },
        config.jwt.secret,
        { expiresIn: '90d' }
      );

      // Set cookie with token
      response.cookie('aimo_token', token, {
        httpOnly: true,
        secure: config.env === 'production',
        sameSite: 'lax',
        path: '/',
        maxAge: 90 * 24 * 60 * 60 * 1000, // 90 days in milliseconds
      });

      // Generate presigned URL for avatar if needed
      let avatarUrl = user.avatar ?? undefined;
      if (avatarUrl && !avatarUrl.startsWith('http')) {
        try {
          avatarUrl = await this.storageService.getPresignedUrl(avatarUrl);
        } catch (error) {
          logger.error('Failed to generate presigned URL for avatar', { error });
        }
      }

      const responseData: LoginResponseDto = {
        token,
        user: {
          id: user.id,
          email: user.email,
          username: user.username,
          avatar: avatarUrl,
        },
      };

      return ResponseUtility.success(responseData);
    } catch (error) {
      logger.error('Registration error:', error);
      if (error instanceof Error && error.message.includes('already exists')) {
        return ResponseUtility.error(ErrorCode.USER_ALREADY_EXISTS);
      }
      return ResponseUtility.error(ErrorCode.DB_ERROR);
    }
  }

  @Post('/logout')
  async logout(@Res() response: Response) {
    // Clear the cookie
    response.cookie('aimo_token', '', {
      httpOnly: true,
      secure: config.env === 'production',
      sameSite: 'lax',
      path: '/',
      maxAge: 0, // Expire immediately
    });

    return ResponseUtility.success(null);
  }

  @Post('/login')
  async login(@Body() loginData: LoginDto, @Res() response: Response) {
    try {
      if (!loginData.email || !loginData.password) {
        return ResponseUtility.error(ErrorCode.PARAMS_ERROR, 'Email and password are required');
      }

      // Find user by email
      const user = await this.userService.getUserByEmail(loginData.email);
      if (!user) {
        return ResponseUtility.error(ErrorCode.USER_NOT_FOUND);
      }

      // Verify password with bcrypt
      const isPasswordValid = await bcrypt.compare(loginData.password, user.password);
      if (!isPasswordValid) {
        return ResponseUtility.error(ErrorCode.PASSWORD_ERROR);
      }

      // Generate JWT token
      const token = jwt.sign(
        {
          id: user.id,
        },
        config.jwt.secret,
        { expiresIn: '90d' }
      );

      // Set cookie with token
      response.cookie('aimo_token', token, {
        httpOnly: true,
        secure: config.env === 'production',
        sameSite: 'lax',
        path: '/',
        maxAge: 90 * 24 * 60 * 60 * 1000, // 90 days in milliseconds
      });

      // Generate presigned URL for avatar if needed
      let avatarUrl = user.avatar ?? undefined;
      if (avatarUrl && !avatarUrl.startsWith('http')) {
        try {
          avatarUrl = await this.storageService.getPresignedUrl(avatarUrl);
        } catch (error) {
          logger.error('Failed to generate presigned URL for avatar', { error });
        }
      }

      const responseData: LoginResponseDto = {
        token,
        user: {
          id: user.id,
          email: user.email,
          username: user.username,
          avatar: avatarUrl,
        },
      };

      return ResponseUtility.success(responseData);
    } catch (error) {
      logger.error('Login error:', error);
      return ResponseUtility.error(ErrorCode.DB_ERROR);
    }
  }
}
